apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: explorer-web-app
  name: explorer-web-app
  namespace: olfyi-0001
spec:
  replicas: 3
  selector:
    matchLabels:
      app: explorer-web-app
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: explorer-web-app
    spec:
      containers:
      - image: ghcr.io/0lnetworkcommunity/explorer/web-app:5449c076e113711e0d6b31ce5876ff51e7b59972
        imagePullPolicy: IfNotPresent
        name: explorer-web-app
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
      imagePullSecrets:
      - name: docker-config
      restartPolicy: Always
