apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.middlewares: olfyi-0001-redirect@kubernetescrd
  name: explorer-data
  namespace: olfyi-0001
spec:
  rules:
  - host: data.0l.fyi
    http:
      paths:
      - backend:
          service:
            name: explorer-data
            port:
              name: http
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - data.0l.fyi
    secretName: explorer-data-tls
