apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
    volume.kubernetes.io/selected-node: libra-explorer-01
    volume.kubernetes.io/storage-provisioner: rancher.io/local-path
  name: postgres-data
  namespace: olfyi-0001
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
  volumeName: pvc-0f306486-d3b7-4510-b43b-8909c4a3b23f
