apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
    volume.kubernetes.io/selected-node: libra-explorer-01
    volume.kubernetes.io/storage-provisioner: rancher.io/local-path
  name: clickhouse-data
  namespace: olfyi-0001
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: local-path
  volumeName: pvc-74586e67-f8f4-417b-ac09-b8b253030025
