apiVersion: v1
kind: Pod
metadata:
  labels:
    app: redis
  name: redis
  namespace: olfyi-0001
spec:
  containers:
  - image: redis
    name: redis
    ports:
    - containerPort: 6379
  serviceAccountName: default
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
