apiVersion: v1
kind: Service
metadata:
  name: explorer-web-app
  namespace: olfyi-0001
spec:
  clusterIP: 10.43.196.131
  clusterIPs:
  - 10.43.196.131

  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: explorer-web-app
