apiVersion: v1
kind: Service
metadata:
  name: explorer-api
  namespace: olfyi-0001
spec:
  clusterIP: 10.43.116.95
  clusterIPs:
  - 10.43.116.95
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: explorer-api
