apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: olfyi-0001
spec:
  clusterIP: 10.43.173.8
  clusterIPs:
  - 10.43.173.8
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 5432
  selector:
    app: postgres
