apiVersion: v1
kind: Service
metadata:
  name: explorer-data
  namespace: olfyi-0001
spec:
  clusterIP: 10.43.41.163
  clusterIPs:
  - 10.43.41.163
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: explorer-data
