apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  namespace: olfyi-0001
spec:
  clusterIP: 10.43.186.217
  clusterIPs:
  - 10.43.186.217
  ports:
  - name: clickhouse
    port: 9000
    targetPort: clickhouse
  - name: http
    port: 8123
    targetPort: http
  selector:
    app: clickhouse
